/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datasheet;

import Archivo.Nuevo;
import Ayuda.AcercaDe;
import DB.BaseDeDatos;
import DB.Variables;
import Edicion.Editar;
import Herramientas.Pass;
import Herramientas.Titulo;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author JOSEF
 */
public class Principal extends javax.swing.JFrame {

    private int t;
    private Vector bus;
    private String datasheet = "Sin archivo";

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        ImageIcon imagen = new ImageIcon("Imgs\\ico.png");
        setIconImage(imagen.getImage());
        setLocationRelativeTo(null);
        this.actualizarTabla();
        jlTitulo.setText(DB.Variables.getTitulo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Individual = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtEncapsulado = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtCodigo = new javax.swing.JTextField();
        jtTipo = new javax.swing.JTextField();
        jtUbicacion = new javax.swing.JTextField();
        jtCantidad = new javax.swing.JTextField();
        jtEstado = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDescripcion = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jbBuscar = new javax.swing.JButton();
        jLimpiar = new javax.swing.JButton();
        jbNew = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jbEliminar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jbDsP = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jlID = new javax.swing.JLabel();
        Listado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jbQuit = new javax.swing.JButton();
        jbDs = new javax.swing.JButton();
        jbEditT = new javax.swing.JButton();
        jbDelete = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbRefesh = new javax.swing.JButton();
        jbSerch = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jtbuscar = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("J L E - IXO V1.2");
        setResizable(false);

        jTabbedPane1.setToolTipText("");

        jlTitulo.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(0, 0, 102));
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("STORE COMPONENTS");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Código:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tipo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Encapsulado:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Ubicación:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Cantidad:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Estado:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Descripción:");

        jtEncapsulado.setEditable(false);
        jtEncapsulado.setBackground(new java.awt.Color(204, 204, 255));
        jtEncapsulado.setToolTipText("Encapsulado del dispositivo");

        jtNombre.setToolTipText("Nombre del elemento");
        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });
        jtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNombreKeyPressed(evt);
            }
        });

        jtCodigo.setEditable(false);
        jtCodigo.setBackground(new java.awt.Color(204, 204, 255));
        jtCodigo.setToolTipText("Código del elemento");

        jtTipo.setEditable(false);
        jtTipo.setBackground(new java.awt.Color(204, 204, 255));
        jtTipo.setToolTipText("Tipo de elemento");

        jtUbicacion.setEditable(false);
        jtUbicacion.setBackground(new java.awt.Color(204, 204, 255));

        jtCantidad.setEditable(false);
        jtCantidad.setBackground(new java.awt.Color(204, 204, 255));
        jtCantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtCantidad.setToolTipText("Cantidad de elementos");

        jtEstado.setEditable(false);
        jtEstado.setBackground(new java.awt.Color(204, 204, 255));
        jtEstado.setToolTipText("Disponible/No disponible");

        jtDescripcion.setEditable(false);
        jtDescripcion.setBackground(new java.awt.Color(204, 204, 255));
        jtDescripcion.setColumns(20);
        jtDescripcion.setRows(5);
        jtDescripcion.setToolTipText("Descrición del dispositivo");
        jScrollPane2.setViewportView(jtDescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNombre)
                            .addComponent(jtCodigo)
                            .addComponent(jtTipo)
                            .addComponent(jtEncapsulado)
                            .addComponent(jtUbicacion)
                            .addComponent(jtCantidad)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtEstado)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtEncapsulado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(jtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(188, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jbBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.setToolTipText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLimpiar.setText("Limpiar");
        jLimpiar.setToolTipText("Limpiar campos");
        jLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpiarActionPerformed(evt);
            }
        });

        jbNew.setText("Nuevo");
        jbNew.setToolTipText("Agregar elemento nuevo");
        jbNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.setToolTipText("Eliminar elemento seleccionado");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbModificar.setText("Editar");
        jbModificar.setToolTipText("Editar elemento seleccionado");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbDsP.setText("Datasheet");
        jbDsP.setToolTipText("Abrir su hoja de datos");
        jbDsP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDsPActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.setToolTipText("Salir de la aplicación");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("No:");

        jlID.setForeground(new java.awt.Color(102, 102, 0));
        jlID.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbNew, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jlID))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jbDsP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, Short.MAX_VALUE)
                                                .addComponent(jbSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addComponent(jSeparator3))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbBuscar)
                .addGap(18, 18, 18)
                .addComponent(jLimpiar)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNew)
                .addGap(18, 18, 18)
                .addComponent(jbEliminar)
                .addGap(18, 18, 18)
                .addComponent(jbModificar)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbDsP)
                .addGap(18, 18, 18)
                .addComponent(jbSalir)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jlID))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout IndividualLayout = new javax.swing.GroupLayout(Individual);
        Individual.setLayout(IndividualLayout);
        IndividualLayout.setHorizontalGroup(
            IndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(IndividualLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        IndividualLayout.setVerticalGroup(
            IndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IndividualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Individual", Individual);

        BaseDeDatos db = new BaseDeDatos();

        Vector resultados = Variables.BD.getDatos();
        Vector columna = new Vector();

        columna.add("No");
        columna.add("Nombre");
        columna.add("Tipo");
        columna.add("Código");
        columna.add("Encapsulado");
        columna.add("Ubicación");
        columna.add("Estado");
        columna.add("Cantidad");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            resultados,columna)
    );
    jTable1.setToolTipText("Listado de dispositivos y elementos");
    jTable1.setFillsViewportHeight(true);
    jTable1.setSelectionBackground(new java.awt.Color(204, 204, 255));
    jTable1.getTableHeader().setReorderingAllowed(false);
    jScrollPane1.setViewportView(jTable1);

    jbQuit.setText("Salir");
    jbQuit.setToolTipText("Salir de la aplicación");
    jbQuit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbQuitActionPerformed(evt);
        }
    });

    jbDs.setText("Datasheet");
    jbDs.setToolTipText("Abrir hoja de datos de elelemento seleccionado en tabla");
    jbDs.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbDsActionPerformed(evt);
        }
    });

    jbEditT.setText("Editar");
    jbEditT.setToolTipText("Editar elemento seleccionado en tabla");
    jbEditT.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbEditTActionPerformed(evt);
        }
    });

    jbDelete.setText("Eliminar");
    jbDelete.setToolTipText("Eliminar seleccionado(s)");
    jbDelete.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbDeleteActionPerformed(evt);
        }
    });

    jbNuevo.setText("Nuevo");
    jbNuevo.setToolTipText("Agregar elemento nuevo");
    jbNuevo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbNuevoActionPerformed(evt);
        }
    });

    jbRefesh.setText("Actualizar");
    jbRefesh.setToolTipText("Actualizar tabla");
    jbRefesh.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbRefeshActionPerformed(evt);
        }
    });

    jbSerch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jbSerch.setText("Buscar");
    jbSerch.setToolTipText("Realizar busqueda");
    jbSerch.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbSerchActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbDs, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbRefesh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jbSerch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator4)))
                            .addComponent(jbNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jbEditT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator5)))))
            .addGap(33, 33, 33))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jbSerch)
            .addGap(18, 18, 18)
            .addComponent(jbRefesh)
            .addGap(13, 13, 13)
            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jbNuevo)
            .addGap(18, 18, 18)
            .addComponent(jbDelete)
            .addGap(18, 18, 18)
            .addComponent(jbEditT)
            .addGap(13, 13, 13)
            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jbDs)
            .addGap(18, 18, 18)
            .addComponent(jbQuit)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jtbuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jtbuscar.setText("Buscar");
    jtbuscar.setToolTipText("Nueva busqueda");
    jtbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jtbuscarMouseClicked(evt);
        }
    });
    jtbuscar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jtbuscarActionPerformed(evt);
        }
    });
    jtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            jtbuscarKeyPressed(evt);
        }
    });

    javax.swing.GroupLayout ListadoLayout = new javax.swing.GroupLayout(Listado);
    Listado.setLayout(ListadoLayout);
    ListadoLayout.setHorizontalGroup(
        ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(ListadoLayout.createSequentialGroup()
            .addGroup(ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addComponent(jtbuscar))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    ListadoLayout.setVerticalGroup(
        ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(ListadoLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Listado", Listado);

    jMenu1.setText("Archivo");

    jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
    jMenuItem2.setText("Nuevo");
    jMenuItem2.setToolTipText("Agregar nuevo");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem2ActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItem2);
    jMenu1.add(jSeparator1);

    jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem4.setText("Salir");
    jMenuItem4.setToolTipText("Salir de aplicación");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem4ActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItem4);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edición");

    jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem1.setText("Editar");
    jMenuItem1.setToolTipText("Editar elemento seleccionado");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem1ActionPerformed(evt);
        }
    });
    jMenu2.add(jMenuItem1);

    jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem9.setText("Actualizar");
    jMenuItem9.setToolTipText("Actualizar tabla");
    jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem9ActionPerformed(evt);
        }
    });
    jMenu2.add(jMenuItem9);

    jMenuBar1.add(jMenu2);

    jMenu6.setText("Herramienta");

    jMenuItem6.setText("Titulo");
    jMenuItem6.setToolTipText("Cambiar título de aplicación");
    jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem6ActionPerformed(evt);
        }
    });
    jMenu6.add(jMenuItem6);

    jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem7.setText("Usuarios");
    jMenuItem7.setToolTipText("Activar cuenta de usuario");
    jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem7ActionPerformed(evt);
        }
    });
    jMenu6.add(jMenuItem7);

    jMenuBar1.add(jMenu6);

    jMenu5.setText("Ayuda");

    jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
    jMenuItem11.setText("Ayuda");
    jMenuItem11.setToolTipText("Sin funcionamiento");
    jMenu5.add(jMenuItem11);

    jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem12.setText("Acerca de...");
    jMenuItem12.setToolTipText("Información de desarrollo");
    jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem12ActionPerformed(evt);
        }
    });
    jMenu5.add(jMenuItem12);

    jMenuBar1.add(jMenu5);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane1)
    );

    jTabbedPane1.getAccessibleContext().setAccessibleName("");

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        //boton para salir del programa
        System.exit(0);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbQuitActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jbNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewActionPerformed
        new Nuevo(this, true).setVisible(true);
    }//GEN-LAST:event_jbNewActionPerformed

    private void jtbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbuscarMouseClicked
        jtbuscar.setText("");
    }//GEN-LAST:event_jtbuscarMouseClicked

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        Variables.nuevo.setVisible(true);
        this.actualizarTabla();
        try{
        bus.clear();}
        catch(NullPointerException e){}
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbRefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefeshActionPerformed
        this.actualizarTabla();
        btEnable();
        jtbuscar.setText("Buscar");//limpia el campo de busqueda
        this.actualizarTitulo();
    }//GEN-LAST:event_jbRefeshActionPerformed

    public void actualizarTitulo() {
        jlTitulo.setText(DB.Variables.getTitulo());
    }
    private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteActionPerformed

        int opt = JOptionPane.showConfirmDialog(null, "¿Desea eliminar?", "Eliminar",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (opt == 0) {//si eliminar
            int[] i = jTable1.getSelectedRows(); //obtenemos el que seleccionamos
            Vector result = Variables.BD.getDatos(); //crea el objeto Base de datos
            //se usa el try por que si no se selecciona ningun registro marca una excepcion
            Vector<Integer> ids = new Vector<Integer>(); //Vector de ids para eliminar
            for (int valor : i) { //obtener ids que se van a eliminar
                Vector registro = (Vector) result.get(valor); //aqui pondra la posicion del seleccionado en la tabla
                ids.add((Integer) registro.get(0));
            }//fin del for mejorado

            if (Variables.BD.eliminarDato(ids)) {  //se hace uso del metodo para eliminar los seleccionador
                actualizarTabla();
                JOptionPane.showMessageDialog(null, "Registro(s) eliminado(s).");
            } else {
                JOptionPane.showConfirmDialog(null, "¡Error al eliminar!", "Error",
                        JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            }
        } else {
            this.actualizarTabla();
        }

    }//GEN-LAST:event_jbDeleteActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        if (Variables.BD.eliminarDatoP(jlID.getText())) {  //se hace uso del metodo para eliminar el seleccionado
            clear();
            JOptionPane.showMessageDialog(null, "Registro eliminado");
            this.datasheet = "Sin archivo";
            actualizarTabla();
        } else {
            JOptionPane.showMessageDialog(null, "Error al eliminar");
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbEditTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditTActionPerformed
        try {
            int i = jTable1.getSelectedRow(); //obtenemos el que seleccionamos
            Vector result = Variables.BD.getDatosT(); //crea el objeto Base de datos
            //se usa el try por que si no se selecciona ningun registro marca una excepcion
            Vector registro = (Vector) result.get(i); //aqui pondra la posicion del seleccionado en la tabla
            Editar regist = new Editar(this, true, registro);//se hace una modificacion en el contructor de la ventana

            regist.setVisible(true);
            actualizarTabla();
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showConfirmDialog(null, "Elemento no seleccionado", "Error",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbEditTActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        actualizarTabla();
        jlTitulo.setText(DB.Variables.getTitulo());
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new Titulo(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
//        new Pass(null, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Variables.nuevo.setVisible(true);
        this.actualizarTabla();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbSerchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSerchActionPerformed
        jTable1 = new javax.swing.JTable();
        jScrollPane1.setViewportView(jTable1);

        String busqueda = jtbuscar.getText();

        if (busqueda.compareTo("") != 0) { //si no escribe nada en el cuadro de texto no buscara nada
            Vector resultados = Variables.BD.buscarDatoT(busqueda);
            Vector columna = new Vector();
            columna.add("ID");
            columna.add("Nombre");
            columna.add("Tipo");
            columna.add("Código");
            columna.add("Encapsulado");
            columna.add("Ubicación");
            columna.add("Estado");
            columna.add("Cantidad");

            jTable1.setModel(new javax.swing.table.DefaultTableModel(resultados, columna));

            jbDelete.setEnabled(false);
            jbEditT.setEnabled(false);
            jbDs.setEnabled(false);
        } else {
            actualizarTabla();
            JOptionPane.showMessageDialog(null, "Introducir busqueda");
            btEnable();
        } //solo actualizara la tabla de nuevo y resetea la busqueda

    }//GEN-LAST:event_jbSerchActionPerformed

    private void jtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbuscarActionPerformed
        jbSerchActionPerformed(evt);
    }//GEN-LAST:event_jtbuscarActionPerformed

    private void jtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbuscarKeyPressed
        if (evt.getKeyCode() == 27) {//27 es el código de la tecla esc //cerra esta ventana
            jtbuscar.setText("");
            actualizarTabla();
            btEnable();
        }

    }//GEN-LAST:event_jtbuscarKeyPressed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        String busqueda = jtNombre.getText();

        if (busqueda.compareTo("") != 0) { //si no escribe nada en el cuadro de texto no buscara nada
            bus = Variables.BD.buscarDatoF(busqueda);

            try {//el try para cuando esta mal el codigo
                jlID.setText(bus.get(0).toString());
                jtNombre.setText(bus.get(1).toString());
                jtTipo.setText(bus.get(2).toString());
                jtDescripcion.setText(bus.get(4).toString());
                jtEncapsulado.setText(bus.get(5).toString());
                jtUbicacion.setText(bus.get(7).toString());
                jtCodigo.setText(bus.get(3).toString());
                jtEstado.setText(bus.get(8).toString());
                jtCantidad.setText(bus.get(9).toString());
                datasheet = bus.get(6).toString();

            } catch (ArrayIndexOutOfBoundsException e) {
                JOptionPane.showMessageDialog(null, "Sin registro");

            }
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        jbBuscarActionPerformed(evt);
    }//GEN-LAST:event_jtNombreActionPerformed

    private void jLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpiarActionPerformed
        bus.clear();
        clear();
    }//GEN-LAST:event_jLimpiarActionPerformed

    private void jbDsPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDsPActionPerformed
        if (datasheet.compareTo("") != 0) {
            if (datasheet.equals("Sin archivo")) {
                JOptionPane.showConfirmDialog(null, "Sin arhivo", "Error",
                        JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
            } else {
                try {
                    File archivo = new File(datasheet);
                    Desktop.getDesktop().open(archivo);
                    System.out.println(archivo.getPath());
                } catch (IOException ex) {
                    JOptionPane.showConfirmDialog(null, "Error", "Error",
                            JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
                } catch (IllegalArgumentException e) {
                    JOptionPane.showConfirmDialog(null, "No encontro arhivo", "Error",
                            JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                }
            }
        }
        this.datasheet = "Sin archivo";
    }//GEN-LAST:event_jbDsPActionPerformed

    private void jtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNombreKeyPressed
        if (evt.getKeyCode() == 27) {//27 es el código de la tecla esc //cerra esta ventana
            jtNombre.setText("");
        }
    }//GEN-LAST:event_jtNombreKeyPressed

    private void jbDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDsActionPerformed
        try {
            int i = jTable1.getSelectedRow(); //obtenemos el que seleccionamos
            Vector result = Variables.BD.getDatosT(); //crea el objeto Base de datos
            //se usa el try por que si no se selecciona ningun registro marca una excepcion
            Vector registro = (Vector) result.get(i); //aqui pondra la posicion del seleccionado en la tabla
            datasheet = registro.get(6).toString();//le paso el path del pdf
            jbDsPActionPerformed(evt);

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Elemento no seleccionado");
        }
    }//GEN-LAST:event_jbDsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jbModificarActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        try {
            Editar regist = new Editar(this, true, bus);//se hace una modificacion en el contructor de la ventana
            regist.setVisible(true);
            actualizarTabla();
        } catch (ArrayIndexOutOfBoundsException e) {
            e.printStackTrace();
            JOptionPane.showConfirmDialog(null, "Elemento no seleccionado", "Error",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
        } catch (NullPointerException e) {
            JOptionPane.showConfirmDialog(null, "Sin elemento", "Error",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        new AcercaDe(null, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed
    public final void actualizarTabla() {

        jTable1 = new javax.swing.JTable();
        Vector resultados = Variables.BD.getDatos();
        int w = resultados.size();

        Vector columna = new Vector();

        columna.add("No");
        columna.add("Nombre");
        columna.add("Tipo");
        columna.add("Código");
        columna.add("Encapsulado");
        columna.add("Ubicación");
        columna.add("Estado");
        columna.add("Cantidad");
        jTable1.setModel(new javax.swing.table.DefaultTableModel(resultados, columna));
        jScrollPane1.setViewportView(jTable1);

    }

    private void btEnable() {
        jbDelete.setEnabled(true);
        jbEditT.setEnabled(true);
        jbDs.setEnabled(true);
    }

    private void clear() {//limpia todos los campos de texto
        jtNombre.setText("");
        jtCodigo.setText("");
        jtTipo.setText("");
        jtEncapsulado.setText("");
        jtUbicacion.setText("");
        jtCantidad.setText("");
        jtEstado.setText("");
        jtDescripcion.setText("");
        jlID.setText("-");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Individual;
    private javax.swing.JPanel Listado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLimpiar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbDelete;
    private javax.swing.JButton jbDs;
    private javax.swing.JButton jbDsP;
    private javax.swing.JButton jbEditT;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNew;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbQuit;
    private javax.swing.JButton jbRefesh;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbSerch;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtCantidad;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextArea jtDescripcion;
    private javax.swing.JTextField jtEncapsulado;
    private javax.swing.JTextField jtEstado;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtTipo;
    private javax.swing.JTextField jtUbicacion;
    private javax.swing.JTextField jtbuscar;
    // End of variables declaration//GEN-END:variables

}
