/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Archivo;

import DB.BaseDeDatos;
import DB.Variables;
import datasheet.Principal;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author JOSEF
 */
public class Nuevo extends javax.swing.JDialog {

    private final boolean insertar = true;
    private String pathPDF;
    private int t;
    private final int v = 0;

    /**
     * Creates new form Agregar
     */
    public Nuevo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon imagen = new ImageIcon("Imgs\\TO-220.png");
        setIconImage(imagen.getImage());
        this.limpiar();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtencapsulado = new javax.swing.JTextField();
        jtnombre = new javax.swing.JTextField();
        jtcodigo = new javax.swing.JTextField();
        jttipo = new javax.swing.JTextField();
        jtcantidad = new javax.swing.JTextField();
        jtubicacion = new javax.swing.JTextField();
        jcestado = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtdescripcion = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jbDS = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jbAceptar = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AGREGAR NUEVO ELEMENTO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Código:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tipo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Encapsulado:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Estado:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Cantidad:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Ubicación:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Descripción:");

        jtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtnombreKeyPressed(evt);
            }
        });

        jtcantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jcestado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disponible", "No disponible" }));
        jcestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcestadoActionPerformed(evt);
            }
        });

        jtdescripcion.setColumns(20);
        jtdescripcion.setRows(4);
        jScrollPane1.setViewportView(jtdescripcion);

        jbDS.setText("Datasheet");
        jbDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDSActionPerformed(evt);
            }
        });

        jbAceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbDS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jbDS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAceptar)
                .addGap(18, 18, 18)
                .addComponent(jbLimpiar)
                .addGap(18, 18, 18)
                .addComponent(jbCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtcodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jttipo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtencapsulado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcestado, javax.swing.GroupLayout.Alignment.LEADING, 0, 186, Short.MAX_VALUE)
                            .addComponent(jtcantidad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtubicacion)
                            .addComponent(jtnombre)))
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jtencapsulado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDSActionPerformed
        if (jtcodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Falta código del elemento");
        } else {
            Variables.codigo = jtcodigo.getText();
            new AddPDF(null, true).setVisible(true);
        }
    }//GEN-LAST:event_jbDSActionPerformed


    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.limpiar();
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        this.emtySpace();

        pathPDF = Variables.archivo;
        String edo;
        Principal p = new Principal();

        Vector registro = new Vector();

        registro.add("");//ID se lo paso vacio por que la base de dato lo pone automaticamente y por que si no lo paso me marca error el vector
        registro.add(jtnombre.getText());//Nombre
        registro.add(jttipo.getText());//Tipo
        registro.add(jtcodigo.getText());//Codigo
        registro.add(jtdescripcion.getText());//Descripcion
        registro.add(jtencapsulado.getText());//Encapsulado
        registro.add(pathPDF);//path del archivo, es decir, donde esta guardado
        registro.add(jtubicacion.getText());//Ubicacion

        if (jcestado.getSelectedIndex() == 0) {
            edo = "Disponible";
        } else {
            edo = "No Disponible";
            jtcantidad.setText("0");
        }
        registro.add(edo);//Estado

        try {
            registro.add(Double.parseDouble(jtcantidad.getText()));//cantidad de elementos en bodega
            if (insertar == true) {
            boolean insertado = BaseDeDatos.getDB().insertarDato(registro); //Retorna valor booleano, true que si fue insertado y falso de lo contrario

            if (insertado) {
                Variables.archivo = "Sin archivo";//esto es para que si agrego otro dispo y no agrego DS no agrege el DS anterior
                p.actualizarTabla();
                JOptionPane.showMessageDialog(this, "Registro guardado");
                this.limpiar();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Error al insertar");
                this.limpiar();
            }
        }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "La cantidad es incorrecta");
        }
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jtnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtnombreKeyPressed
        if (evt.getKeyCode() == 27) //27 es el código de la tecla esc //cerra esta ventana
        {
            if (jtnombre.getText().isEmpty()) {
                this.dispose();
            } else {
                this.limpiar();
            }
        }

    }//GEN-LAST:event_jtnombreKeyPressed

    private void jcestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcestadoActionPerformed
        if (jcestado.getSelectedIndex() == 1) {
            jtcantidad.setEnabled(false);
        }
        if (jcestado.getSelectedIndex() == 0) {
            jtcantidad.setEnabled(true);
        }
    }//GEN-LAST:event_jcestadoActionPerformed

    private void emtySpace() {
        if (jtnombre.getText().isEmpty()) {
            jtnombre.setText("-");
        }

        if (jttipo.getText().isEmpty()) {
            jttipo.setText("-");
        }

        if (jtencapsulado.getText().isEmpty()) {
            jtencapsulado.setText("-");
        }

        if (jtubicacion.getText().isEmpty()) {
            jtubicacion.setText("-");
        }

        if (jtdescripcion.getText().isEmpty()) {
            jtdescripcion.setText("-");
        }

        if (jcestado.getSelectedIndex() == 1) {
            jtcantidad.setText("0");
        }

        if (jcestado.getSelectedIndex() == 0) {
            jtcantidad.getText().isEmpty();
        }

    }

    public void limpiar() {
        jtnombre.setText("");
        jttipo.setText("");
        jtcodigo.setText("");
        jtdescripcion.setText("");
        jtencapsulado.setText("");
        jtubicacion.setText("");
        jcestado.setSelectedIndex(0);//que ponga disponible
        jtcantidad.setText("");

    }

    private int enumeracion() {
        Vector result = BaseDeDatos.getDB().getDatos();

        int x = result.size();
        return x + 1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Nuevo dialog = new Nuevo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbDS;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JComboBox jcestado;
    private javax.swing.JTextField jtcantidad;
    private javax.swing.JTextField jtcodigo;
    private javax.swing.JTextArea jtdescripcion;
    private javax.swing.JTextField jtencapsulado;
    private javax.swing.JTextField jtnombre;
    private javax.swing.JTextField jttipo;
    private javax.swing.JTextField jtubicacion;
    // End of variables declaration//GEN-END:variables
}
